### ISSUE TITLE
Typical PR workflow fails if repo doesn't have issues enabled

### ISSUE THREAD

**Issue by dagolden** [ingydotnet/git-hub#117]
If issues are disabled, you can't use the issue API to comment, close, etc.

Instead, one has to use the PR API.  That means we need at least these:

* pull-comment
* pull-close

**Comment by perlpunk** [comment]
It seems to work now; I tested `pr-new`, `comment` and `issue-close` with a repo which has issues disabled. So I guess this was changed.

**Comment by ingydotnet** [comment]
OK. Closing.
