### ISSUE TITLE
when command fails, contents of the editor are forever lost

### ISSUE THREAD

**Issue by karenetheridge** [ingydotnet/git-hub#126]
In https://github.com/ingydotnet/git-hub/pull/124 I made a code error (still not sorted out), which is now resulting in 'git hub issue-new' to fail.  Unfortunately I'd typed up a long bug report and when the command failed, the contents of the editor were lost.

The scratch file created by the editor should be preserved, and its path printed out, if the command did not execute correctly, so I can retrieve what I just typed and resubmit (or go to the web to paste).

**Comment by perlpunk** [comment]
this should work better now after merging #206.
thanks
