### ISSUE TITLE
`git hub fork` doesn’t respect `--org` option when adding remote

### ISSUE THREAD

**Issue by 8573** [ingydotnet/git-hub#149]
I used `git hub fork` with the `--org` command-line option to fork a
GitHub repository into the custody of a GitHub organization that I
control:

    $ git hub fork wesnoth/website --org='8680-wesnoth' --remote='fork'
    git remote add fork git@github.com:8573/website.git
    Repository 'wesnoth/website' forked to '8680-wesnoth'
    $ git remote -v
    fork    git@github.com:8573/website.git (fetch)
    fork    git@github.com:8573/website.git (push)
    origin  git@github.com:wesnoth/website.git (fetch)
    origin  git@github.com:wesnoth/website.git (push)

The remote repository name `fork` was defined as referring to the
nonexistent repository `git@github.com:8573/website.git`, as if I had
been forking the repository not to an organization, when I believe it
ought to have been defined as referring to the repository
`git@github.com:8680-wesnoth/website.git`.

**Comment by perlpunk** [comment]
@8573 this should be fixed with PR #205

**Comment by perlpunk** [comment]
@8573 in master now
closing, thanks!
