### ISSUE TITLE
pr-list should use the current repos's owner by default

### ISSUE THREAD

**Issue by agentzh** [ingydotnet/git-hub#159]
My `opsboy` repository is in the organization account `openresty` while my own account is `agentzh`. So while in the opsboy checkout, `pr-list` tries to fetch PRs for the non-existent `agentzh/opsboy` location instead of the correct one, `openresty/opsboy`. Hopefully `pr-list` can always use the current clone location by default :) It took me a while to figure out why I cannot see your latest PR for opsboy ;)

```
agentzh@imac ~/git/opsboy (pegex)$ git hub pr-list
Pull requests for 'agentzh/opsboy' (state=open):

agentzh@imac ~/git/opsboy (pegex)$ git hub pr-list openresty/opsboy
Pull requests for 'openresty/opsboy' (state=open):
#1   (open)   Pegex
     @ingydotnet   Created: 2015-03-14  Updated: 2015-03-14
     ingydotnet:pegex → openresty:pegex
```

**Comment by agentzh** [comment]
Okay, not just `pr-list`, but also many other commands like `comment` and `issue-close`.

**Comment by ingydotnet** [comment]
From IRC:

    ingy | agentzh: the way it is supposed to work is that if you are cd'd in a repo dir, then if a git-hub command needs a repo name it uses that one by default
    ingy | if it needs an owner it should take the user or org                                                                      
    ingy | I'll try it in your repo and gist it here                                                                                
    ingy | agentzh: look at https://gist.github.com/99ae45ff5a3d751cc0a4                                                            
    ingy | this works as I think it should

**Comment by agentzh** [comment]
@ingydotnet Okay, my bad. The repos was originally cloned by `agentzh/opsboy`. It works because of github's automatic redirection feature (opsboy was moved from `agentzh` to `openresty`). Sorry for the noise!

**Comment by ingydotnet** [comment]
No problem. I'm glad you figured that out. I was scratching my head.
