### ISSUE TITLE
Naming conflict with github/hub

### ISSUE THREAD

**Issue by christianbundy** [ingydotnet/git-hub#160]
GitHub's [`hub`](https://github.com/github/hub) has the same name – how are you planning to resolve this?

**Comment by psophis** [comment]
GitHub's hub is a wrapper for the git command. This adds a subcommand.

**Comment by christianbundy** [comment]
Right, but sharing both the name and the domain (even if the usage is slightly different) is still a naming conflict. It seems that `git hub` also overlaps with `hub`, meaning that both of the following do the same thing:

``` shell
hub clone github/hub
```

``` shell
hub hub clone github/hub
```

**Comment by pixelwitches** [comment]
"hub clone" and "git hub clone" are obviously two different things.

**Comment by Ciantic** [comment]
I think the confusion here is that github/hub is awfully difficult to overview, we have no idea what commands it has.

Compare the synopsis of this great subcommand to github/hub, and you see. They are not in conflict.

I think this subcommand is far clearer in what it does.

**Comment by ingydotnet** [comment]
There's really no naming conflict, and actually no usage conflict. ie you can use both of them together:

```
hub hub clone github/hub
```

Closing this, as I don't think there is a problem to solve here.
