### ISSUE TITLE
can't clone on windows

### ISSUE THREAD

**Issue by mattn** [ingydotnet/git-hub#161]
See https://github.com/ingydotnet/git-hub/tree/master/test/commands

some directory name are contained `:`. it is reserved letter for file path on windows.

![](http://go-gyazo.appspot.com/d7adabb34e4993a2.png)

**Comment by sutt** [comment]
Yes same here, very annoying! remove the colon I think?

**Comment by mattn** [comment]
Yes.

**Comment by ingydotnet** [comment]
Thanks for the report. I haven't heard of anyone getting this to work on Windows because it really needs bash 3.2 (and probably some Windows love after that).

I've heard of a popular git environment that offers Bash 3.1, but can't recall the name of it.

I can go ahead and rename the test files, but it might just be the start of a long road. If you have time to help me get this working, I'll be glad to do my part.

**Comment by mattn** [comment]
it's not problem of bash since git on windows bundle bash. it is problem of file-system.

**Comment by ingydotnet** [comment]
I understand that the naming problem. But the other problem is that (iirc) git bundles bash 3.1 and git-hub needs bash 3.2. I could be mistaken, but could you check which version of bash you is bundled?

**Comment by dolmen** [comment]
The project is [msysgit](https://msysgit.github.io/)

**Comment by ingydotnet** [comment]
@dolmen, right and that project is stuck on Bash 3.1. 

I remember now, this is all in an issue for git-subrepo: https://github.com/ingydotnet/git-subrepo/issues/38#issuecomment-91032121

**Comment by sutt** [comment]
So you can get the repo with browser > download-zip but still couldn't get it to work after adding it to path.

**Comment by ingydotnet** [comment]
The basic deal is that msysgit provides ancient Bash 3.1. I code to Bash 3.2 (still ancient) for OSX reasons.

There is an msysgit issue here that I just commented on: https://github.com/msysgit/msysgit/issues/193#issuecomment-112910585

Looks like the msysgit author is open to accepting a PR here. Any takers?!

**Comment by ingydotnet** [comment]
I'll fix the : in filesys part now.

**Comment by ingydotnet** [comment]
I changed the `:`chars to `+` chars.

I tested that they are valid in win32 file paths.

Can someone test that the repo now clones?

**Comment by ingydotnet** [comment]
BTW, how does msysgit work?

I installed it on my windows vm, but I'm not sure how to use it and couldn't locate the docs.

**Comment by mattn** [comment]
Thanks but 4 files still not.
https://github.com/ingydotnet/git-hub/blob/master/ext/bashplus/test/source-bash%2B-:std.t
https://github.com/ingydotnet/git-hub/blob/master/ext/json-bash/ext/test-more-bash/ext/bashplus/test/source-bash%2B-:std.t
https://github.com/ingydotnet/git-hub/blob/master/ext/test-more-bash/ext/bashplus/test/source-bash%2B-:std.t
https://github.com/ingydotnet/git-hub/blob/master/plugin/git-hub-travis/ext/test-more-bash/ext/bashplus/test/source-bash%2B-:std.t

**Comment by ingydotnet** [comment]
@mattn, I forgot about the subrepos. Fixed this. Can you test again?

**Comment by mattn** [comment]
i confirmed repo is fixed. thanks. however, to work on windows, i must add many hacks.

**Comment by ingydotnet** [comment]
@mattn thanks.

If you decide to work on this, please open issues for the various windows issues. I'll attempt to help out as much as I can.
