### ISSUE TITLE
Homebrew installation?

### ISSUE THREAD

**Issue by vitorgalvao** [ingydotnet/git-hub#165]
Is a [homebrew](https://github.com/Homebrew/homebrew) formula planned?

**Comment by btrd** [comment]
https://github.com/Homebrew/homebrew/pull/31886
No new since a long time :disappointed:

**Comment by btrd** [comment]
Did you find a solution ?

**Comment by vitorgalvao** [comment]
No, but keeping the issue open isn’t doing any good, since the issue is already being discussed on homebrew.

**Comment by jonafato** [comment]
I'm working on bringing Homebrew/homebrew#31886 back to life in Homebrew/homebrew#41299. Open to feedback / input on the blockers (currently: better tests) if anyone here has suggestions.
