### ISSUE TITLE
Add gist commands

### ISSUE THREAD

**Issue by frioux** [ingydotnet/git-hub#175]
I would love some gist stuff; like maybe off the top of my head:

```
gists
gist-clone
```

so I could `git hub gists -r | xargs -n1 git hub gist-clone`

**Comment by perlpunk** [comment]
I started working on it, if you wanna try it out:
https://github.com/perlpunk/git-hub/tree/2015-07-09-gists

**Comment by ingydotnet** [comment]
@frioux, just an FYI on the xargs…

This does the same thing:

    git hub gists -r | git hub gist-clone -

You probably knew that, but just commenting for posterity.

The `-` inserts 1 line from STDIN and `=` inserts one word from STDIN:

    echo perlpunk frioux | git hub follow =

Also `@` always expands to your user id, which is sometimes a handy sugar for
poor typists like me.

**Comment by perlpunk** [comment]
I wrote a little vim function for fun that calls gist-new:
https://gist.github.com/perlpunk/5d8a540f0e4a8cf29a21

**Comment by perlpunk** [comment]
so the most important commands are implemented, I think.
I would like to let `git hub gist` display the filenames, but that should wait until json-bash has a keys function

**Comment by perlpunk** [comment]
I added gist-fork
