### ISSUE TITLE
`git hub` does not show help on mac

### ISSUE THREAD

**Issue by jenspinney** [ingydotnet/git-hub#186]

**Comment by raimue** [comment]
Cannot reproduce. Without more details I would assume this was just an installation issue.

**Comment by jenspinney** [comment]
@ingydotnet made this issue from my account (while pairing). I blame him for the lack of details :P 

This was also a while ago, so maybe something changed and it works now.

**Comment by perlpunk** [comment]
@jenspinney ok thanks, then I'll close this for now.
