### ISSUE TITLE
`orgs` does not list private repos

### ISSUE THREAD

**Issue by frioux** [ingydotnet/git-hub#190]
I assumed that `git hub orgs -A` would fix it, but it does not.

**Comment by perlpunk** [comment]
`$title =~ s/repos/organizations/ # ?`

That would be a different API call.
The simple solution would be to decide depending on if the username equals the authenticated login.

**Comment by frioux** [comment]
I'm sorry, I meant private organizations

-- 
sent from a rotary phone, pardon my brevity

**Comment by ingydotnet** [comment]
Used @perlpunk++'s strategy. Seems solid. Good catch @frioux.
