### ISSUE TITLE
I encounter a permission issue while cloning

### ISSUE THREAD

**Issue by eduOS** [ingydotnet/git-hub#212]
After I enter `git hub clone ingydotnet/git-hub` I meet a permission denied (publickey) error. It reads `Could not read from remote repository, please mak esure you have the correct access rights and the repository exists.`. I suppose I may get wrong by two means: 1) the name or the owner of the repository is wrong. But I find it is not. 2) I have not set the configure file right. Here is what the .config file has:
```
[git-hub]
login = eduOS
api-token = my token
use-auth = true
json-lib = json-perl.bash
```

Could you please tell me where the problem lies? Thanks in advance.

**Comment by eduOS** [comment]
It guides me to use -v for more information. And I conjecture maybe I should change `git@github.com` to `https://` format.

**Comment by perlpunk** [comment]
If you run the command with `-v` you an see what the clone command is. It clones via ssh. Canyou clone directly via ssh?

**Comment by perlpunk** [comment]
I guess a `--http` option would be helpful...

**Comment by eduOS** [comment]
In most cases I cannot given that I am not allowed to. But I can use `git clone git://` or `git clone https://` for all public repositories. Why should git-hub only allow the private protocal?

**Comment by perlpunk** [comment]
Or maybe a `protocol` config variable would be more helpful.
I think most users would want to use ssh to work with the cloned repository, but on a machine where you don't have a key, you would want http for every repository.

**Comment by eduOS** [comment]
Oh, get it. I have not set a global ssh key. But for this problem I've solved it by adding the following script to the .zshrc:
```
gitclone(){
    git clone https://github.com/$1/$2.git
}
```
But I'd better add a ssh key.
Thanks.

**Comment by eduOS** [comment]
@perlpunk Sorry. I've refreshed the ssh key but failed to run it around. Could you please tell me how to set the ssh key as you said? I followed [this tutorial](http://help.github.com/articles/generating-an-ssh-key): http://help.github.com/articles/generating-an-ssh-key.  Many thanks.

**Comment by perlpunk** [comment]
You need to do three things:
* Create a key on your machine
* Make sure this key is used for github.com (either it is your default key, or you configure it in .ssh/config)
* Upload the public key to your github account https://github.com/settings/ssh

If you followed the tutorial, maybe you could say what you have done exactly so far?

**Comment by eduOS** [comment]
I thought the problem lies in the second step. Here is the setting in the ssh config file:
```
Host eduOS
HostName github.com
User git
IdentityFile ~/.ssh/key_for_github
```

Since I have more than one account on GitHub so I changed the host name to my account name.

**Comment by eduOS** [comment]
PS: I can push changes to my account without entering password and account name.

**Comment by perlpunk** [comment]
I see.
git-hub clones repositories with the hostname github.com. It's not possible to confiure that right now.
Also for other commands which interact with the repo it expects the hostname to contain github.com.

What _would_ work is setting the host alias manually to something like `github.com-username`. For repos which are already cloned, then some git-hub commands like `git hub repo` should work like expected.
But this wouldn't work for cloning. Also, git-hub only supports one user/token in the global config right now.

So to really support different github users, we'd need to
* support more than one github user by
 * allowing several user/tokens in the config
 * checking out git-hub in different locations per github user (as soon as it is possible to read the configuration from there)
 * alternatively you could set GIT_HUB_USER_DIR to `~/.git-hub-username`
* support configuring the github hostname (which would be useful for other purposes too)

So for now, I'm afraid you're basically restricted to one user or a lot of manual work :-/

**Comment by perlpunk** [comment]
Or, well, a more pragmatic solution for now could be to create a small wrapper script for each user:
```shell
GIT_SSH_COMMAND="ssh -i identityfile" GIT_HUB_LOGIN=username GIT_HUB_API_TOKEN=abc123 \
  git hub "$@"
```

be careful where to store your token though! =)

**Comment by eduOS** [comment]
Thanks.

**Comment by eduOS** [comment]
@perlpunk I've tackled it by adding a default ssh key with the host name as github.com.
