### ISSUE TITLE
Support .netrc for github password/token

### ISSUE THREAD

**Issue by perlpunk** [ingydotnet/git-hub#218]
People might want to store their github password and/or token in a netrc file.

This file is a good place to store all your passwords if you need them
to be read automatically.

netrc files can also be encrypted, if the netrc loader supports that.

For reading netrc there's already the perl core module Net::Netrc

```
machine github.com login gh-login password topsecret
machine api.github.com login gh-login password api-token
```

``` perl
use Net::Netrc;
my $cred = Net::Netrc->lookup("api.github.com", $user);
my $token = $cred->password;
```

**Comment by perlpunk** [comment]
see #219

**Comment by dolmen** [comment]
Yes, of course. That will be easier for malwares to find interesting credentials.
