### ISSUE TITLE
Print error message on 410

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-hub#72]
git hub issues -O
Issues for 'ingydotnet/onebusaway-iphone' (state=open):
{
  "message": "Issues are disabled for this repo",
  "documentation_url": "https://developer.github.com/v3/issues/"
}
Error: 'git hub issues' command failed: 410

**Comment by perlpunk** [comment]
This command seems to work now also for repos with issues disabled.

**Comment by perlpunk** [comment]
@ingydotnet  Closing this now
please reopen if necessary
